- .github/workflows/PR.yml
- .github/workflows/main.yml
- Dockerfile
- README.md
- deploy.R
This PR adds functionality to automatically deploy to shinyapps.io for each pull request and merge to main. (Thanks to [this blog post](https://www.r-bloggers.com/2021/02/deploy-to-shinyapps-io-from-github-actions/).)
The environmental variables are set so that the app will be pushed into to my shiny app account (`nami-techimpact`) for now.
Fixes #14
> Auto-Deploy to Shinyapps.io

- Dockerfile
- app/advocates_panel.r
- app/home_panel.r
- app/server.R
- app/ui.R
- app/www/style.css
This PR adds a page for advocates. We are testing out a page that local organizers can use to find out the information about the housing voucher. I included a multi-input selector for GEOIDs.
This PR also includes a tweak for the radio button on the Home page. The radio button is rendered as a normal button, via the `shinyWidgets` package. This improves the experience for mobile users (fixes #28).
I also separated different panels into different files---so that tracking changes later will be easier.
> Add the page for advocates (+ UI tweaks)

- app/advocates_panel.r
- app/counties_panel.R
- app/methods_panel.R
- app/ui.R
- app/www/style.css
This PR adds headings and placeholders for the tabs for the advocates and the by-county comparisons.
@mehak25 : I indicated the places for visualizations in the text (e.g., `(*Add a pie chart for the overview? receiving vs not receiving)`). Can you take a look at the test app and go to tabs `For Advocates` and `By County` (after deployment)?
https://nami-techimpact.shinyapps.io/housing-voucher-test/
Feel free to merge the pull request if you think that's ok.
> Add headings and placeholders for the advocates and by-county comparison tabs

- app/Scripts/county.R
- app/www/style.css
This PR fixes small typos (fix #50) and makes the bar plots horizontal. 
I also modified the `county.R` file to reduce the code re-use--I bundled common ggplot layers into a list and reuse them throughout.
> Fix typos & make bar plots horizontal

- app/Scripts/county.R
- app/server.R
This PR orders counties in a consistent manner, fixing #56.
I also made the use of color consistent so that we are depicting voucher participants as green and those who are not served as orange. 
The PR also includes various tweaks including repositioning legends and optimizing the plotting routine.
> Order counties in a consistent manner & color changes

- app/Scripts/county.R
- app/home_panel.r
- app/scripts/advocates.R
- app/scripts/county.R
- app/scripts/plotly_settings.R
- app/server.R
This PR disables zoom and other tools (`modebar`) in the plotly visualizations (fixes #66).
I created a separate R file to document the plotly settings. (`plotly_settings.R`)
Also, I renamed the `Script` folder to `script`, so that the folder naming is consistent with other folders in this repo.
> Disable zoom in plotly visualizations 

- app/advocates_panel.r
- app/www/style.css
This PR adds a footnote to the advocate's table, describing the following:
- "10" = there are 10 or fewer counts for the households receiving a voucher 
- "NA" = HUD does not report data for the given census tract
Fixes #67
> Add a footnote for the table describing `10` and `NA`

- app/scripts/county.R
- app/scripts/plot_prop_counties.R
- app/server.R
This PR updates the tooltip of the pie chart, so that it shows "Eligible Families", instead of "Families":
Fixes #78 
This PR also includes small changes to tooltips:
1. The tooltips for the number of eligible families will only show counts. I had to rename the variables to achieve this because the ggplotly's tooltip option will show the variable name
2. I removed the tool tip for the horizontal bar chart showing the proportion of renters across counties. I don't think we have pertinent information that we can add to the graph via tooltips (for now)
> Update the labels in the pie chat tooltips to "Eligible Families"

- app/server.R
This PR adds functionality to route to the advocate's page via a unique URL. When the app is accessed with a URL parameter `page=advocates`, the app will show the advocates page. (e.g., https://nami-techimpact.shinyapps.io/housing-voucher/?page=advocates)
Fixes #97
> Add a unique URL redirecting to the advocates page

- app/www/style.css
This PR adjusts the maximum widths of the headings so that they will not break into 3 lines on widescreen.
I also adjusted the background color of the headings to a bit darker one (`#e1e6ed`) so that it will show on screens with lesser contrast. (I was looking at the app with my external monitor, and the previous color (`#f7fbff`) was almost indistinguishable from white.
Fix #98
> Adjust the maximum width of the headings to avoid breaking into 3 lines

- .Rprofile
- app/server.R
This PR fixes the bug where we cannot run the app on Windows. (Fixes #93)
Suspected root causes:
1. The original `.Rprofile` file was referring to the command `python3`. On Windows, the command will redirect to a Windows store version of Python. I fixed this by setting the command `python` if the OS is Windows.
2. Corrupt virtual environment. I realized that the virtual environment installed via reticulate was corrupt. I did `reticulate::virtualenv_remove()` to remove the environment. I fixed this issue by creating a unique name for the virtual environment for this repo (to avoid overlaps with other projects).
Next step is to check if @mehak25 can run the app on her machine! 🤞
> Run the app on Windows

- app/advocates_panel.r
- app/server.R
- app/www/style.css
This PR updates the table and the graph on the advocate's view via flexbox. It uses `flex-wrap` to wrap the table and the graph when viewing on a mobile device.
> Layout the table and the graph on the advocates view

- app/advocates_panel.r
This PR:
1. adds a line break to the table footnote, avoiding breaking in the middle of the action link (fixes #120), and
2. updates the label of the download button so that the label will simply say "Download" (fixes #119)
> Add a line break to the table footnote & update the label of the download button

- app/advocates_panel.r
- app/home_panel.r
- app/server.R
This PR changes the name of the advocates page to "Explore Your Neighborhood" (fixes #105):
The PR also includes a change in the CTA button label to be consistent with this change. The CTA button is labeled "Explore Your Neighborhood":
> Rename the advocates page to the "Explore Your Neighborhood" 

- app/advocates_panel.r
- app/scripts/plot_prop_census.R
- app/server.R
- app/www/style.css
This PR includes fixing the address search bar (fixes #128).
The PR also includes:
- Cleanups for reducing duplicate codes and routines
- Re-design of the message field of the address search bar so that it shows (a) an example when there is no input, and (b) shows a census tract when the value is looked up.
- Disable zoom and hide the mode bar from the barplot
Further thoughts: I think it's better if we have a loading spinner on that lookup bar. Currently, there is no feedback after clicking the magnifier icon.
> Fix and reposition the address search bar

- app/home_panel.r
This PR updates the title of the app into a question (fix #131):
"How is Delaware doing to help families in a housing crisis?"
> Make the title of the app into a question

- app/home_panel.r
This PR changes the title of the call-to-action card for the renters, to "Are you struggling to pay rent?" (fixes #132). The new title broadens the audience to anyone who is struggling (not only those with 30% or more rent spending on income).
> Broaden the audience for the renters ("Are you struggling to pay rent?")

- app/www/style.css
This PR makes the background image of the title responsive. Now, the background image of the title changes size depending on the window widths (instead of tiling).
Fixes #133
> Make the background image responsive for the title 

- app/www/style.css
#155 made the background responsive for the title, but not for the last call-to-action. This PR does for the last CTA.
> Make the background responsive for the last CTA

- .github/workflows/PR.yml
Currently, the auto-deployment to shinyapps.io fails intermittently. This PR updates the workflow for the PR so that the action will retry by itself.
> Add a retry to the PR workflow

- .github/workflows/main.yml
This PR fixes the workflow when merging into the main. #159 introduced a bug where the deployment commands were using the codes from the workflows for PR submissions (see https://github.com/de-data-lab/voucher-eligibility/actions/runs/1924774275).
> Fix the main workflow

- app/www/style.css
This PR changes the color of the CTA buttons to Tech Impact Orange `#ED8B00`. (fixes #136)
I used this tool https://www.0to255.com/ed8b00 to pick increasingly darker colors for the hover `#cb7700` and active `#a96300` states.
> Change the color of the CTA buttons to TI orange

- app/home_panel.r
- app/www/style.css
This PR adds cards to display the main points on the homepage (fixes #137). This PR also includes a fix for the issue where the action cards had different widths (#127).
Along the way, I realized that I had max-widths applied to the child elements (lists within the cards). I was wondering why I could not change the widths.
Reminder to self to check the child elements ✅
> Use cards to display main points on the homepage

- app/home_panel.r
This PR moves the citations below the heading (fixes #139). Previously, the citations were at the bottom of the icon.
> Move the citations below the heading

- app/scripts/plot_counts_counties.R
- app/scripts/plot_prop_census.R
- app/scripts/plot_prop_counties.R
- app/scripts/plot_table_desc.R
- app/scripts/plotly_settings.R
- app/server.R
This PR makes the backgrounds of the plots transparent (fixes #140). Previously, the backgrounds were white.
To implement, I had to make two changes:
1. I made the background transparent by changing the paper color on plotly `layout()`
2. I used a transparent background on the ggplot side `theme()`
Only changing the bg color on plotly only results in changing the bg color around the chart (bg for titles etc.), but not the bg color within the chart.
> Make the backgrounds of the plots transparent

- app/advocates_panel.r
- app/www/style.css
This PR adds a margin around the title part of the explore tab (fixes #166). Previously, there was no margin to the title of the explore app, and thus no y-margin was present. This PR wraps the title and the description into a div and adds a uniform margin around it.
> Add a margin to the title part of the explore tab

- docs/index.Rmd
This PR adds exploratory visualizations comparing the number and proportions of rent-burdened (30%) and severely rent-burdened (50%) households across census tracts. 
The PR adds a visualization comparing how this disparity between non-severe and severe rent burdens correlates with the proportions of eligible households receiving a voucher.
All visualizations are available on the GitHub page. (No changes on the app)
> Explore 30% vs 50% households

- docs/index.Rmd
This PR adds residual plots and an exploratory interaction model to explore whether the proportions of non-severe and severely burdened renters predict the voucher service rate. All changes are on the GitHub page.
> Explore residual plots & interactions comparing non-severe and severely burdened renters

- app/home_panel.r
This PR adds a background explaining the threshold for rent burden (fixes #138). This will guide the reader better about 30%/50% differences later.
> Add a background story about 30%/50% rent-burden thresholds

- app/counties.R
- app/home_panel.r
This PR focuses on the story about the proportions chart to Sussex County.
Currently, we have two stories in that chart: (a) New Castle doing the best, and (b) Sussex doing the worst. Focusing on Sussex doing the worst makes sense to highlight the overall situation that the vouchers are not going to a majority of eligible families.
> Focus the story on Sussex County in the proportions chart

- app/home_panel.r
This PR tweaks the title of the app to be: "How is Delaware helping families in a housing crisis?". Fixes #169.
> Tweak the title of the app

- app/advocates_panel.r
- app/www/style.css
This PR changes the CTA of the explore page to a question, "How is your neighborhood doing?". Fixes #144.
> Change the call-to-action text of the explore page to "How is your neighborhood doing?"

- README.md
- app/server.R
This PR updates the URL parameter ref to the explore tab (`?page=explore`, to be consistent with the title of the tab (fixes #126).
Previously, it was `?page=advocates`.
The PR also includes updates to the README file.
> Use `?page=explore` to navigate to the explore tab

- app/server.R
This PR updates the tooltips for the pie chart:
The PR removes the count values for brevity & simplicity.
Completes a subtask in #151
> Update the tooltips for the pie chart

- app/scripts/plot_counts_counties.R
- app/server.R
This PR improves the tooltips of the horizontal bar chart for counts, by converting it to a full Plotly chart as below (finish fixing #151).
> Improve tooltips and convert the horizontal bar chart showing counts to Plotly

- README.md
This PR fixes the level of the heading for the Renviron file in README.
> Fix the heading level in the README file

- app/ui.R
This PR moves the JS rendering the logo to the footer in the `navbarPage` to remove the empty element in the navbar. Fixes #201
> Move the JS for the logo into the footer to remove the empty element in the navbar

- app/advocates_panel.r
- app/scripts/plot_table_desc.R
- app/server.R
- app/www/style.css
This PR fixes the issue of the tooltips wrapping weirdly (fixes #221).
The root of the problem was that the wrapping function was applied at the stage of the text template. The wrapping widths did not carry over to the rendered text, and thus the text was not wrapping correctly.
This PR fixes this issue by manually setting up the tooltip texts.
Along the way, I converted non-tidy scripts to tidy codes in hopes of increasing the readability of the code.
This PR also includes small styling changes for the title of the plot (fixes #227).
Screenshot:
> Fix the tooltip breaks via tidying and manually setting up tooltip texts

- app/scripts/plot_prop_census.R
This PR makes the y-position of the label for the selected census tracts responsive to the maximum value of y, thus avoiding overlapping labels. Fixes #240
> Avoid overlapping labels on the explore page

- app/advocates_panel.r
- app/scripts/plot_prop_census.R
- app/server.R
- app/www/style.css
This PR improves the description for the vertical bar chart by:
1. adding an in-line dropdown menu
2. describing the percentile rank for the selected tracts (used eCDF for estimation)
This PR also includes small style changes and reordering of the elements on the explore page. 
Fixes #219
> Improve the description for the vertical bar chart

- app/CTA.html
- app/explore_panel.R
- app/home_panel.r
This PR adds a CTA to the explore page. The PR creates a separate HTML file for the CTA component and renders it to both the home page and the explore page. 
Fixes #238
> Add CTA to the explore page

- app/explore_panel.R
- app/scripts/plot_prop_census.R
- app/scripts/plot_table_desc.R
- app/server.R
- app/www/style.css
This PR replaces the 30% vs. 50% labels with the "rent-burdened" vs. "severely rent-burdened" labels. Doing so makes the labels consistent across the app.
Fixes #252
> Consistently label rent-burdened and severely rent-burdened groups

- app/www/style.css
This PR removes horizontal whitespaces from the hero image, via removing x-paddings from the container.
Fixes #259
> Remove horizontal whitespaces from the hero image
