de-data-lab/voucher-eligibility

- output/EDA.Rmd
> Create new summary plots

- app/server.R
Fixes for #17 (hopefully). I was not able to recreate the issue on my local. I changed the timing of dropping the `sf` geometry earlier to see if that fixes the issue. Will check the deployed test app.
> Change the timing of dropping geometry earlier

- app/server.R
This PR updates the labels for the pie chart. I also removed the legend from the chart, and adjusted padding to the title.
> Update labels for the pie chart

- docs/index.Rmd
> Added count visualizations

- Dockerfile
- app/footer.html
- app/server.R
- app/ui.R
- app/www/style.css
This PR makes the app a page with a navigation bar. The home page has a one-column layout. 
The PR also includes some style changes and the addition of the footer.
I also added content:
- the main text shows the proportion of potentially-eligible people receiving a housing voucher in Delaware. 
- the call to action section encourages visitors to take action on the housing crisis
> Change UI to a Navigation Bar Page layout & Add a Call to Action

- README.md
This PR adds descriptions of the environmental variables used for this repo so that anyone cloning can replicate the results.
> Add descriptions about the environmental variables

- docs/index.Rmd
Added table and plots for above 30 and above 50 count of eligible people
> Added plots for 30 and 50 above

- src/census.Rmd
Added census.Rmd that uses census API to download and save ACS data in csv files in data/raw/ folder
> Added census.Rmd

- app/advocates_panel.r
- app/counties_panel.R
- app/server.R
Added visuals to advocates and county tabs.
> Integrating visuals to app

- app/counties_panel.R
- app/server.R
Added reactive elements to select 30% or 50% eligibility in county tab
> Added reactive elements to select 30% or 50% eligibility

- app/Scripts/advocates.R
- app/Scripts/county.R
- app/server.R
Added county labesl.
Added rows with 0 number reported in HUD.
Separated code script for each tab.
> Worked on pending issues

- app/Scripts/advocates.R
- app/advocates_panel.r
- app/server.R
- docs/index.Rmd
Added clickable map to advocates tab
> Added amp to advoctes tab

- Dockerfile
- app/Scripts/advocates.R
Added library tigris to advocates.R
> Added library tigris

- app/Scripts/advocates.R
- app/advocates_panel.r
- app/server.R
- app/www/style.css
Change output for advocates table.
> Formated Advocates table

- app/advocates_panel.r
- app/counties.R
- app/home_panel.r
- app/server.R
- app/ui.R
- app/www/style.css
This PR makes the app to be one-page. 
- Adds an overarching title, and some contexts (the voucher program exists, and that is effective)
- Adds a horizontal bar plot showing the proportions of serviced renters who are potentially eligible
- Implements a button to go to the tab for advocates
Fixes #47
> Try a scrolling storytelling format

- app/advocates_panel.r
- app/server.R
Added functionality to download data from table in advocates panel.
> Added Download in Advoc table

- app/scripts/advocates.R
- app/server.R
improved map visual by changing fillColor and highlights
> improved map visual

- app/advocates_panel.r
This PR fixes a typo on a heading. (Fix #77 )
> Fix a typo

- README.md
This PR adds the URLs to advocate tools to the README file.
> Add URLs to the advocate tools to README

- app/home_panel.r
- app/www/style.css
This PR adds background color to the main point cards (fixes #102). Thanks, @hmaldreis for the design help!
This PR also includes 
1. re-ordering the call to action cards (fixes #103).
2. bolding the title and making it bigger (fixes #104)
<details>
<summary>See screenshot</summary>
</details>
> Add a background color to the main point cards and reorder the homepage

- app/advocates_panel.r
- app/www/style.css
Removed space under download button
> Fixing space under download button

- Dockerfile
- app/advocates_panel.r
- app/scripts/advocates.R
- app/scripts/plot_table_desc.R
- app/scripts/update_map.R
- app/server.R
- app/www/style.css
- src/add_geometry_to_ACS_HUD.R
> Issues 148,149, 145

- app/www/style.css
This PR updates the font to Roboto throughout the app (fix #134).
The PR imports the regular (400) and bold (700) weights of Roboto.
> Update the font to Roboto

- .github/workflows/main.yml
#158 added a retry to the deployment workflow. This PR adds the same workflow for merging to the main.
> Retry at a failed deployment when merging to the main branch

- app/advocates_panel.r
- app/scripts/advocates.R
- app/scripts/plot_prop_census.R
- app/scripts/plot_table_desc.R
- app/scripts/update_map.R
- app/server.R
- app/www/style.css
- docs/index.Rmd
> Zoom control, Clear All, Bar plot labels

- app/advocates_panel.r
- app/scripts/plot_counts_counties.R
- app/scripts/plot_prop_census.R
- app/scripts/plot_table_desc.R
- app/server.R
Removed axis labels from figures and added tooltip to figures on Explore page
> Worked on issues #142 and #151

- app/advocates_panel.r
- app/www/style.css
This PR puts the "Clear All" button into the map (fix #183).
The PR also tweaks the CSS for the buttons and the messages on the map to align better.
> Put "Clear All" button into the map & tweak CSS

- Dockerfile
- app/server.R
This PR Fixes the download buttons (fixes #196). Previously, the download buttons were not generating CSV files. (due to the column names not specified correctly).
> Fix the download buttons

- app/methods_panel.R
- app/www/style.css
This PR adds data sources to the methods section (fixes #85).
> Add data sources to the methods section

- app/advocates_panel.r
- app/server.R
- app/www/style.css
This PR makes the map sticky on the explore page and re-layouts the contents on the page (fixes #202, #204).
> Make the map sticky on the explore page & re-layouting

- app/advocates_panel.r
- app/counties.R
- app/scripts/advocates.R
- app/scripts/plot_prop_census.R
- app/scripts/plot_table_desc.R
- app/scripts/update_map.R
> Summary plots

- app/advocates_panel.r
- app/server.R
This PR fixes the issue of the description about the chart not showing up on the explore page (fixes #211).
> Fix the description about the chart to show up on the page

- app/advocates_panel.r
- app/server.R
- app/www/style.css
This PR fixes the issue of the explore map not showing up in a skinny window (fixes #212).
> Fix to show the map in a skinny window

- app/scripts/plot_table_desc.R
- app/server.R
- app/www/style.css
This PR fixes the issue of the chart labels cutting off from the bar chart on the explore page.
The PR also reduces code redundancy in the hopes of improving readability.
> Prevent the chart labels from cutting off & reduce code redundancy

- app/advocates_panel.r
- app/scripts/plot_prop_census.R
- app/server.R
Added new summary.
Added title to second plot.
> Addning new summary and title to bar plot

- README.md
This PR moves the app from my personal account to Tech Impact's shinyapps.io account.
The PR also updates the README file.
The app is now available here:
https://techimpact.shinyapps.io/housing-voucher
Closes #176
> Deploy the app to Tech Impact's shinyapps.io account

- app/scripts/plot_table_desc.R
This PR moves the legend of the horizontal bar graph to the top.
Fixes #231
> Move the legend of the horizontal bar graph to the top

- README.md
This PR adds an overview section to README with the following information:
1. A background of the voucher program and what the app does
2. Data source
3. Why we are making this app open-source, and an invitation to submit an issue
Fixes #255
> Add an overview section to README

- README.md
This PR adds badges for the production and testing app to README.
> Add badges for production and testing app to README
